# Site settings
name: YangLe Blog
email: 540363207@qq.com
author: YangLe
url: http://www.yangle520.com
resume_site: http://www.yangle520.com/tag/
github: https://github.com/yangle520/
baseurl: ""
#description: 副标题描述
#meta_description: 杨乐;个人博客
motto: It's our wits that make us men.
banner: 学而不思则罔，思而不学则殆。

#permalink: /:categories/:year/:month/:day/:title/
permalink: /:year/:month/:day/:title/
paginate: 10

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']

github_username: yangle520

# Build settings
markdown: kramdown

baidu_analysis: 

