title: YangLe
email: 540363207@qq.com
author: YangLe
copyright: "Unpublished Work (cleft) 2017-{currentYear} {author}"
baseurl: ""
url: http://yangle520.github.io
github: https://github.com/yangle520/
favicon: ""
yat:
  date_format: "%b %d, %Y"
markdown: kramdown

header_pages:
  - index.html
  - archives.html
  - categories.html
  - tags.html

# Pagination setting
paginate: 10